---
- name: Tomcat deployment playbook
  hosts: tomcat       
  become: yes               
  vars:
    tomcat_ver: 9.0.52                          
    ui_manager_user: manager                    
    ui_manager_pass: Str0ngManagerP@ssw3rd     
    ui_admin_username: admin                    
    ui_admin_pass: Str0ngAdminP@ssw3rd          
  roles:
    - tomcat

